config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'events#index'
  resources :users, only: [:edit, :update, :show]
  resources :photos, only: [:create, :destroy]
  resources :events do
    resources :attends, only: %i(index create destroy)
  end
end

app/models/attend.rb
# == Schema Information
#
# Table name: attends
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  event_id   :integer
#  created_at :datetime
#  updated_at :datetime
#

class Attend < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  event_id   :integer          not null
#  user_id    :integer          not null
#  content    :text             not null
#  created_at :datetime
#  updated_at :datetime
#

class Comment < ActiveRecord::Base
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  content    :text             not null
#  user_id    :integer          not null
#  location   :string(255)
#  start_at   :datetime
#  end_at     :datetime
#  created_at :datetime
#  updated_at :datetime
#

class Event < ActiveRecord::Base
  belongs_to :user
  has_many :attends
  has_many :users, through: :attends
  has_many :photos

  scope :attend, -> (user_id) { where user_id: user_id }
  scope :planning, -> { where('start_at > ?', DateTime.now) }
  scope :finished, -> { where('end_at < ?',   DateTime.now) }
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  event_id   :integer
#  image      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Photo < ActiveRecord::Base
  validates :user_id, :event_id, :image, presence: true

  belongs_to :user
  belongs_to :event

  mount_uploader :image, ImageUploader
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  event_id   :integer          not null
#  name       :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Tag < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string(255)
#  account                :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable
  has_many :attends
  has_many :events, through: :attends
  has_many :photos
  has_many :organizing_events, class: Event, foreign_key: :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attends_controller.rb
class AttendsController < ApplicationController
  before_action :find_event

  def create
    @attend = @event.attends.build(attend_params)
    @attend.save!
    # redirect_to @event
  end

  def destroy
    @attend = @event.attends.where(id: params[:id]).first
    @attend.destroy
    redirect_to @event
  end

  private

  def find_event
    @event = Event.where(id: params[:event_id]).first if params[:event_id]
  end

  def attend_params
    params.require(:attend).permit(:user_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_event

  def index
    @events = Event.order(:id).all
    @attended_planning_events = current_user.events.planning.order(:id)
    @attended_finished_events = current_user.events.merge(Event.finished).order(:id)
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.organizing_events.build(event_params)
    render 'new' and return unless @event.save
    redirect_to events_path
  end

  def show
  end

  def edit
  end

  def update
    @event.update(event_params)
    redirect_to event_path(@event)
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private

  def find_event
    @event = Event.where(id: params[:id]).first if params[:id]
  end

  def event_params
    params.require(:event).permit(:title, :location, :start_at, :end_at, :content)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
    @photo = current_user.photos.build(photo_params)
    @photo.save!
    redirect_to event_path(@photo.event)
  end

  private
  def photo_params
    params.require(:photo).permit(:event_id, :user_id, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user

  def show
  end

  def update
    @user.update_attributes!(user_params)
    redirect_to user_path(@user)
  end

  private

  def find_user
    @user = User.where(id: params[:id]).first if params[:id]
  end

  def user_params
    params.require(:user).permit(:name, :account, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attends_helper.rb
module AttendsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_attend.html.slim
- if @event.user_ids.include? current_user.id
  - attend = @event.attends.where(user_id: current_user.id).first
  = link_to "参加取消", event_attend_path(@event.id, attend.id), method: :delete, class: "btn btn-danger"
- else
  = form_tag event_attends_path(event), method: :post, remote: true do
    = hidden_field_tag "attend[user_id]", current_user.id
    = submit_tag "参加する", class: "btn btn-success"

app/views/events/_form.html.slim
h1 イベントの#{message}

.row
  .col-xs-8

    = form_for event, class: "form" do |f|
      .form-group
        = f.label :title, "タイトル"
        .input-group
          .input-group-addon
            i.glyphicon.glyphicon-asterisk
          = f.text_field :title, class: "form-control"

      .form-group
        = f.label :location, "場所"
        = f.text_field :location, class: "form-control"

      .form-group
        = f.label :start_at, "開始日時"
        = f.text_field :start_at, class: "form-control datetimepicker"

      .form-group
        = f.label :end_at, "終了日時"
        = f.text_field :end_at, class: "form-control datetimepicker"

      .form-group
        = f.label :content, "内容・詳細"
        .input-group
          .input-group-addon
            i.glyphicon.glyphicon-asterisk
        = f.text_area :content, class: "form-control", size: "x5"


      = f.submit message, class: "btn btn-success"

coffee:
  $ ->
    $('.datetimepicker').datetimepicker()

app/views/events/_list.html.slim
- if events.empty?
  p.no-content
    | 表示すべきイベントはありません。
- else
  table.table.table-striped.table-condensed
    tr
      th タイトル
      th 内容
      th 主催者
    - events.each do |event|
      tr
        - event = event.decorate
        td = link_to event.title, event_path(event)
        td = event.short_content
        td = event.user_name

app/views/events/_photo_form.html.slim
= form_for photo, class: 'form' do |f|
  .modal.fade.photo-modal tabindex="1" role="dialog" aria-labelledby="mayModalLabel" aria-hidden="true"
    .modal-dialog
      .modal-content
        .modal-header
          button.close type="button" data-dismiss="modal"
            span aria-hidden="true"
              | &times;
              span.sr-only Close
          h4.modal-title#myModalLabel 写真投稿
        .modal-body
            .form-group
              = f.label :image
              = f.file_field :image
            =f.hidden_field :event_id, value: photo.event.id
        .modal-footer
          button.btn.btn-default type="button" data-dismiss="modal"
            | キャンセル
          = f.submit "投稿", class: "btn btn-primary"
            | 投稿

app/views/events/edit.html.slim
= render 'form', event: @event, message: '更新'

app/views/events/index.html.slim
h1 イベント

= link_to new_event_path, class: "btn btn-sm btn-primary" do
  i.glyphicon.glyphicon-plus


.panel.panel-default.event-panel
  .panel-heading
    ul.nav.nav-tabs role="tablist"
      li
        a href="#all" role="tab" data-toggle="tab" すべて
      li
        a href="#will" role="tab" data-toggle="tab" 参加予定
      li
        a href="#past" role="tab" data-toggle="tab" 参加済

  .tab-content
    .tab-pane#all
      = render 'list', events: @events

    .tab-pane#will
      = render 'list', events: @attended_planning_events

    .tab-pane#past
      = render 'list', events: @attended_finished_events
coffee:
  $ ->
    $('.nav-tabs a:first').click()

app/views/events/new.html.slim
= render 'form', message: "登録", event: @event, message: '作成'

app/views/events/show.html.slim
- @event = @event.decorate


.row
  .col-xs-8
    .panel.panel-default
      .panel-heading
        h3 = @event.title
        .controls.pull-right
          = link_to edit_event_path(@event), class: "btn btn-sm btn-primary" do
            i.glyphicon.glyphicon-pencil
          = link_to event_path(@event), method: :delete, data: {confirm: '削除してよろしいですか？'}, class: "btn btn-sm btn-danger" do
            i.glyphicon.glyphicon-trash

      / .panel-body
      table.event-show-table.table.table-condensed.table-striped
        tr
          th 場所
          td = @event.location
        tr
          th 開始日時
          td = @event.start_at
        tr
          th 終了日時
          td = @event.end_at
        tr
          th 主催者
          td = @event.user_name
        tr
          th 概要
          td = @event.content

    .panel.panel-warning
      .panel-heading
        h3 写真
        .controls.pull-right
          button.btn.btn-sm.btn-success data-toggle="modal" data-target=".photo-modal"
            | 写真投稿
          = render 'photo_form', photo: @event.photos.build

      .panel-body
        - @event.photos.select{ |e| ! e.image_url.nil? }.each do |photo|
          a.group01 href=photo.image_url  title=(@event.title + "  投稿者：" + photo.user.name)
            img src=photo.image_url(:thumb) width="100" alt=""
  .col-xs-4
    .attend-area
      = render 'attend', event: @event

      .attended-user-list
        h3 参加者一覧
        ul
        - @event.users.each do |user|
          - user = user.decorate
          li = user.name

javascript:
  $(document).ready(function(){
    console.log("ready");
    $(".group01").colorbox({rel:'group01', transition:"none", width:"70%", height:"70%"});
  });

app/views/layouts/application.html.slim
doctype html
html lang="ja"
  head
    title
      | SSS
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-default role="navigation"
      .container-fluid
        .navbar-header
          a.navbar-brand href="/" SSSS

        .collapse.navbar-collapse
          ul.nav.navbar-nav
            li
              a href="#" link
            li
              a href="#" link
            li
              a href="#" link
          - if current_user
            ul.nav.navbar-nav.navbar-right
              li
                = link_to "profile", user_path(current_user)
              li
                = link_to "logout", destroy_user_session_path, method: :delete
    .container-fluid
      = yield

app/views/users/_form.html.slim
h1 ユーザ#{message}

.row
  .col-xs-6
    = form_for user, class: "form" do |f|
      .form-group
        = f.label :name, "氏名"
        = f.text_field :name, class: "form-control"

      .form-group
        = f.label :account, "アカウント名"
        = f.text_field :account, class: "form-control"

      .form-group
        = f.label :email, "メールアドレス"
        = f.text_field :email, class: "form-control"

      = f.submit message, class: "btn btn-success"

app/views/users/edit.html.slim
= render 'form', user: current_user, message: "更新"

app/views/users/show.html.slim
h1 ユーザ情報
= link_to edit_user_path(current_user), class: "btn btn-sm btn-primary" do
  i.glyphicon.glyphicon-pencil
= link_to "パスワード変更", edit_user_password_path, class: "btn btn-sm btn-warning"

table
  tr
    th  氏名
    td  = @user.name
  tr
    th  アカウント名
    td  = @user.account
  tr
    th  メールアドレス
    td  = @user.email